name: stgcnpp
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - numpy>=1.24
  - tqdm>=4.65
  - pip:
      - torch>=2.0
      - torchvision>=0.15
      - opencv-python>=4.7
      - ipython>=8.38.0
      - ipynb>=0.5.1
      - matplotlib