name: joints2smpl
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - matplotlib
  - pandas
  - tensorboardx
  - einops
  - tqdm
  - trimesh
  - joblib
  - open3d
  - chumpy
  - pip:
      - --index-url https://download.pytorch.org/whl/cu124
      - --extra-index-url https://pypi.org/simple
      - torch==2.10.0
      - torchvision==0.25.0
      - torchaudio==2.10.0
      - h5py
      - smplx
      - git+https://github.com/facebookresearch/pytorch3d.git
