name: joints2smpl
channels:
  - conda-forge
  - pytorch3d
  - default
dependencies:
  - python=3.10
  - pip
  - numpy
  - matplotlib
  - pandas
  - tensorboardx
  - einops
  - tqdm
  - trimesh
  - joblib
  - open3d
  - chumpy
  - pytorch
  - torchvision
  - torchaudio
  - pytorch3d
  - pip:
      - h5py
      - smplx
